### ISSUE TITLE
Latest 1.16 causes "declared locally but not exported" error

### ISSUE THREAD

**Issue by danewalton** [Azure/azure-iot-hub-node#8]
Getting this error when using the latest `1.16`:

```
Module '"./dist/connection_string"' declares 'ConnectionString' locally, but it is not exported.
```

https://github.com/Azure/azure-iot-middleware-freertos/actions/runs/3491532894/jobs/5844277832#step:9:3614

**Comment by ethanann-ms** [comment]
PR #9
